/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Column: typeof import('./src/components/column.vue')['default']
    DateModifiedColumnEntry: typeof import('./src/components/date-modified-column-entry.vue')['default']
    FsTree: typeof import('./src/components/fs-tree.vue')['default']
    NameColumnEntry: typeof import('./src/components/name-column-entry.vue')['default']
    NameNode: typeof import('./src/components/name-node.vue')['default']
    SizeColumnEntry: typeof import('./src/components/size-column-entry.vue')['default']
  }
}
