// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Column: typeof import('./src/components/column.vue')['default']
    DateModifiedColumnEntry: typeof import('./src/components/date-modified-column-entry.vue')['default']
    FsTree: typeof import('./src/components/fs-tree.vue')['default']
    NameColumnEntry: typeof import('./src/components/name-column-entry.vue')['default']
    NameNode: typeof import('./src/components/name-node.vue')['default']
    SizeColumnEntry: typeof import('./src/components/size-column-entry.vue')['default']
  }
}

export {}
