// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FsTree: typeof import('./src/components/fs-tree.vue')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    TreeNode: typeof import('./src/components/tree-node.vue')['default']
  }
}

export {}
